import Head from 'next/head'


import Nabar from '../components/Nabar'
import Herobanner from '@/components/Herobanner'
import Footer from '@/components/Footer'
import Signinpage from '@/components/Signinpage'




export default function Home() {
 
  return (
    <div className='bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ...'>
      <Head>
        <title>Trading Application</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Signinpage/> */}
      <Herobanner/>
      
     
      {/* <Footer/> */}
      

     
    </div>
  )
}
